add trash counter scaffold
Lexima/4ocean-dawn pull request #1
Opened 2022-06-14 10:25 UTC by olafghanizadeh

2022-07-30 05:28 UTC, olafghanizadeh commented
I am still missing an icon export from Sam here

2022-07-31 16:36 UTC, lanceylexima requested changes

2022-07-31 16:36 UTC, lanceylexima commented on sections/trash-tracker.liquid
> +                <p class="trash-tracker__subtitle">
This should be an h2-h6 heading and not a P tag.

2022-07-31 16:36 UTC, lanceylexima commented on sections/trash-tracker.liquid
> +            {%- if section.settings.subtitle -%}
This should be "title" variable since its not a subtitle of the section

2022-08-31 16:30 UTC, merged